name: final_final
description: This example showcases object detection within a live feed from a USB camera.
ports: []
bricks:
- arduino:video_object_detection: {
      variables: {
      EI_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/ei-models/arduino_colors.eim
    }
}
- arduino:web_ui: {}
icon: 📽️
